#{ pkgs, ... }:
#let
#portalocker-fixed = pkgs.python3.pkgs.portalocker.overrideAttrs (old: {
#doCheck = false;
#});
#python-packages = pkgs.python313.withPackages (
#  ps: with ps; [
#    portalocker-fixed
#    requests
#    pyquery
#  ]
#);
#in
{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    _64gram
    a2jmidid
    abseil-cpp
    acl
    adbfs-rootless
    add-determinism
    adw-gtk3
    adwaita-fonts
    adwaita-icon-theme
    adwaita-icon-theme-legacy
    adwaita-qt
    adwaita-qt6
    adwsteamgtk
    afew
    agate
    agenix-cli
    alot
    alsa-lib
    alsa-lib-with-plugins
    alsa-oss
    alsa-plugins
    alsa-plugins-wrapper
    alsa-firmware
    alsa-tools
    alsa-topology-conf
    alsa-ucm-conf
    alsa-utils
    alsa-utils-nhlt
    alsaequal
    angryoxide
    anydesk
    anyrun
    apparmor-bin-utils
    apparmor-pam
    apparmor-parser
    apparmor-profiles
    apparmor-teardown
    apparmor-utils
    appimage-run
    apulse
    aquamarine
    aria2
    asha-pipewire-sink
    agg
    ags
    aiac
    aj-snapshot
    alejandra
    alibuild
    ams
    ananicy-rules-cachyos
    angle
    angular-language-server
    ansible-builder
    ant
    anyrun
    appimage-run
    apktool
    app2unit
    #argo
    arxiv-latex-cleaner
    ashell
    asm-lsp
    astal.astal3
    astroid
    astro-language-server
    audacity
    autobuild
    autoconf
    autogen
    awk-language-server
    ayugram-desktop
    b43FirmwareCutter
    b43Firmware_6_30_163_46
    baobab
    baresip
    basedpyright
    #pkgs.bash
    #pkgs.bashdb
    #pkgs.bashly
    #pkgs.bashNonInteractive
    #pkgs.bashrun2
    #pkgs.bash-language-server
    bazel-remote
    bibata-cursors
    bemenu
    bemoji
    bind
    #bintools
    #pkgs.binutils
    #pkgs.binutils-unwrapped-all-targets
    binwalk
    biome
    #pkgs.bison
    #pkgs.bisoncpp
    bkt
    ble-serial
    blend2d
    blender
    blueman
    bluetuith
    bluez
    bluez-alsa
    bluez5
    bluez5-experimental
    bluez-headers
    bluez-tools
    bmputil
    boost
    bootc
    #bootspec-lix
    bottles
    bottom
    brightnessctl
    broadcom-bt-firmware
    brotli
    browserpass
    btdu
    btop
    btrfs-progs
    boost-build
    buck2
    build2
    buildah
    buildbot
    buildcatrust
    buildifier
    pkgs.buildkit
    pkgs.buildkit-nix
    pkgs.buildpack
    bun
    #bzip2
    c3d
    cacert
    cachix
    calamares-nixos
    calamares-nixos-extensions
    caligula
    captive-browser
    cargo
    catgirl
    cava
    ccache
    ccls
    ccrypt
    certstrap
    checkmake
    crystalline
    curl
    curlpp
    pkgs.curl-impersonate
    pkgs.curl-impersonate-ff
    cfv
    clamav
    pkgs.clang
    pkgs.clang_multi
    pkgs.clang-tools
    cliphist
    clips
    clojure-lsp
    cmake
    cmake-language-server
    cmrt
    cod
    codex
    colord
    commonsCompress
    compose2nix
    conda
    conftest
    connmanFull
    connman_dmenu
    conntrack-tools
    coppwr
    cope
    copyPkgconfigItems
    coqPackages.coq-lsp
    coreutils
    cpufrequtils
    cpuid
    cpu-x
    crane
    crate2nix
    crates-lsp
    crc64fast-nvme
    csvs-to-sqlite
    ctags-lsp
    cudaPackages.cuda_cccl
    #cudaPackages.cuda_cudart
    cudaPackages.cuda_cuobjdump
    #cudaPackages.cuda_cupti
    cudaPackages.cuda_cuxxfilt
    cudaPackages.cuda_demo_suite
    cudaPackages.cuda_documentation
    cudaPackages.cuda_gdb
    cudaPackages.cuda_nsight
    cudaPackages.cuda_nvcc
    cudaPackages.cuda_nvdisasm
    cudaPackages.cuda_nvml_dev
    cudaPackages.cuda_nvprof
    cudaPackages.cuda_nvprune
    cudaPackages.cuda_nvrtc
    cudaPackages.cuda_nvvp
    cudaPackages.cuda_opencl
    cudaPackages.cuda_profiler_api
    cudaPackages.cuda_sandbox_dev
    cudaPackages.cuda_sanitizer_api
    cudaPackages.cudatoolkit
    cudaPackages.cudnn
    cudaPackages.cudnn-frontend
    cudaPackages.cusparselt
    cudaPackages.cutensor
    cudaPackages.libcublas
    cudaPackages.libcusparse
    cudaPackages.libnvjitlink
    cudaPackages.libnvjpeg
    cudaPackages.markForCudatoolkitRootHook
    cudaPackages.nccl
    cudaPackages.nsight_compute
    cudaPackages.nvidia_fs
    #cudaPackages.tensorrt
    cudatoolkit
    cuelsp
    curl
    darkly
    dcap
    dcgm
    dconf
    dconf2nix
    dconf-editor
    dbt
    dbus
    dbus-broker
    dbus_cplusplus
    dbus-glib
    dbus_java
    deadnix
    defaultPkgConfigPackages.MagickWand
    degate
    delsum
    desktop-file-utils
    dev86
    dfu-programmer
    dfu-util
    dependency-track
    deputy
    #pkgs.diffutils
    directx-shader-compiler
    discordo
    discord-gamesdk
    discourse
    distcc
    distccMasquerade
    distccWrapper
    dmenu
    dmenu-bluetooth
    dmenu-wayland
    dns-root-data
    docker
    docker-buildx
    docker-language-server
    #dotty
    dot-language-server
    dotnet-runtime
    dri-pkgconfig-stub
    drm_info
    drone-runner-docker
    dts-lsp
    dua
    duf
    dunst
    dwl
    dysk
    easyeffects
    #edid-decode
    edk2
    eggdbus
    egl-wayland
    eglexternalplatform
    elasticsearch
    elf-header-real
    elfdeps
    elfutils
    elfio
    ember-language-server
    embree
    emmet-language-server
    enzyme
    eresi
    ethtool
    extra-cmake-modules
    facetimehd-firmware
    f3d
    fake-gcs-server
    fastfetch
    faust
    faust2alsa
    fcitx5
    fcitx5-gtk
    fcitx5-material-color
    fcitx5-rime
    fcitx5-skk
    fcitx5-tokyonight
    fdroidserver
    fdtools
    fetchutils
    fennel-ls
    filter-audio
    #pkgs.findutils
    firefox
    firefox-devedition
    #firefox-wayland
    firefoxpwa
    ffmpeg
    fh
    file-roller
    #firmware-manager
    firmware-updater
    #flake-edit
    #flake-checker
    flaresolverr
    flex
    flutter
    font-util
    fpm2
    fprintd
    freeglut
    freetype
    freerdp
    frog-protocols
    fsearch
    ftgl
    fuzzel
    fwup
    fwupd
    fwupd-efi
    gamemode
    gamenetworkingsockets
    gamescope
    pkgs.gawk
    gcab
    pkgs.gcc
    pkgs.gcc_multi
    pkgs.gcc_debug
    pkgs.gdb
    gdu
    gegl
    pkgs.getent
    geticons
    pkgs.gfortran
    gh
    gi-docgen
    pkgs.glib
    pkgs.glibc
    pkgs.glibcLocales
    glew
    glucose-syrup
    gmime
    gmp
    gnat
    gnome-menus
    gnome.nixos-gsettings-overrides
    gobject-introspection
    godot
    gom
    gprbuild
    graphicsmagick
    grimblast
    gsettings-qt
    ghidra
    ghostty
    ginko
    git
    git-credential-gopass
    git-credential-keepassxc
    git-credential-manager
    git-filter-repo
    git-lfs
    gitlab-ci-ls
    gitoxide
    git-secrets
    git-vendor
    glib
    #glfw-wayland
    glm
    glslang
    glsl_analyzer
    glslls
    #glxinfo
    gn
    gnome-icon-theme
    gnugrep
    pkgs.gnumake
    pkgs.gnused
    pkgs.gnutar
    gob2
    gom
    gopass
    gopass-hibp
    gopass-jsonapi
    google-amber
    gopls
    gpgme
    grim
    gssdp_1_6
    gtest
    gthree
    gummi
    gusb
    gxml
    #gzip
    h8mail
    harfbuzzFull
    harmonia
    hcxtools
    hdrop
    heimdall
    helm
    helm-ls
    helvum
    hicolor-icon-theme
    holo-build
    hsphfpd
    htmx-lsp2
    hw-probe
    hwinfo
    hwloc
    hydra
    hypnotix
    hyprcursor
    hyprdim
    hyprgraphics
    hypridle
    hyprland
    hyprland-activewindow
    hyprland-autoname-workspaces
    hyprland-monitor-attached
    hyprland-per-window-layout
    hyprland-protocols
    hyprland-qt-support
    hyprland-qtutils
    hyprland-workspaces
    hyprland-workspaces-tui
    hyprlandPlugins.hyprexpo
    hyprlang
    hyprpanel
    hyprpaper
    hyprpicker
    hyprpolkitagent
    hyprprop
    hyprshade
    hyprshell
    hyprshot
    hyprsome
    hyprsunset
    hyprsysteminfo
    hyprutils
    hyprwayland-scanner
    hyprlock
    hyprls
    hyprmagnifier
    hyprnome
    hyprpanel
    hyprpaper
    hyprpicker
    hyprpolkitagent
    hyprprop
    hyprshade
    hyprshell
    hyprshot
    hyprsome
    hyprsunset
    hyprsysteminfo
    hyprutils
    hyprviz
    hyprwayland-scanner
    imapfilter
    keepmenu
    keepwn
    libsForQt5.fcitx5-qt
    libsecret
    polkit
    nwg-dock-hyprland
    pyprland
    rose-pine-hyprcursor
    icecream
    iconConvTools
    iconic
    iconnamingutils
    icon-library
    icon-slicer
    ifdtool
    igsc
    include-what-you-use
    inetutils
    inputplumber
    intelephense
    inteltool
    inxi
    ipbus-uhal
    iptsd
    ipu6-camera-bins
    iputils
    ipxe
    ispc
    itch
    #ivsc-firmware
    jade
    jamesdsp-pulse
    java-language-server
    javacc
    jdk
    jdt-language-server
    jinja-lsp
    jitsi
    jj
    john
    johnny
    journalwatch
    jsonnet-language-server
    jq
    jql
    just-lsp
    k9s
    kcl-language-server
    kdePackages.breeze-icons
    kdePackages.dolphin
    kdePackages.fcitx5-with-addons
    kdePackages.fcitx5-configtool
    kdePackages.fcitx5-qt
    kdePackages.partitionmanager
    kdePackages.qt6ct
    kdePackages.qtwayland
    kdePackages.qtstyleplugin-kvantum
    keychain
    khal
    ktx-tools
    khronos-ocl-icd-loader
    kitty
    killall
    kmod
    kmscon
    kmsvnc
    kotlin-language-server
    ktls-utils
    lasuite-meet
    lcms
    ldc
    lefthook
    lemminx
    libadwaita
    libapparmor
    libassuan
    libbpkg
    libbutl
    libcanberra
    libcap_ng
    libdbusmenu
    libdbusmenu-gtk2
    libdbusmenu-gtk3
    libdecor
    libdrm
    libesmtp
    libfprint
    libgcc
    libgbm
    libgee
    libgmpris
    libgudev
    libglut
    libhandy
    libiconv
    pkgs.libidn2
    libminc
    libinput
    libipt
    pkgs.libllvm
    libmediaart
    libmemcached
    libnfnetlink
    libnixxml
    libnotify
    libodb-sqlite
    libopenaptx
    liboqs
    libosinfo
    libpeas
    libpeas2
    libpkgconf
    libplacebo
    librearp
    librime
    librsvg
    libsForQt5.qt5ct
    libsForQt5.qtdbusextended
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qtwayland
    libsForQt5.qt5.qtwayland
    libsearpc
    libsigcxx30
    libsfdo
    libsodium
    libssh
    libssh2
    libsysprof-capture
    libtool
    libv4l
    libva
    libva1
    libvpl
    libxcb
    libxcb-render-util
    libomxil-bellagio
    libunistring
    libuvc
    libxdg_basedir
    libxsmm
    limine
    linux-firmware
    linuxHeaders
    linux-pam
    linyaps
    lix
    lkl
    lksctp-tools
    lldb
    llm-ls
    pkgs.llvm
    llvmPackages_21.compiler-rt
    llvmPackages_21.libllvm
    llvmPackages.libc
    llvmPackages_21.llvm
    llvmPackages_21.mlir
    loupe
    louvre
    lshw
    ltex-ls-plus
    lttng-tools
    lua51Packages.luarocks
    lua51Packages.luarocks_bootstrap
    lua51Packages.luarocks-build-rust-mlua
    lua51Packages.luarocks-build-treesitter-parser
    lua5_1
    luau-lsp
    luajitPackages.luarocks_bootstrap
    luajitPackages.luarocks
    luajitPackages.lua
    luajitPackages.magick
    lucide
    lsp-plugins
    lssecret
    lv2
    lyrebird
    lzip
    m4
    mailcap
    maildrop
    mailsend
    mailutils
    makejinja
    mako
    manim
    mariadb
    marksman
    material-design-icons
    maturin
    maven
    md-lsp
    mdx-language-server
    #mcp-nixos
    meilisearch
    me_cleaner
    menu-cache
    meson
    mesonlsp
    meson-tools
    metabase
    microcode-intel
    millet
    mimalloc
    mimeo
    mimic
    mkcert
    mlflow-server
    mold
    monkeysphere
    morewaita-icon-theme
    moshi
    mpack
    mpfr
    mpls
    mricron
    mstflint
    musl
    n2
    nar-serve
    ncdu
    neomutt
    neovim
    nerdfix
    networkmanager
    networkmanagerapplet
    networkmanager_dmenu
    networkmanager-iodine
    networkmanager-l2tp
    networkmanager-openconnect
    networkmanager-strongswan
    next-ls
    nh
    nil
    nimlangserver
    nimlsp
    ninja
    niri
    niriswitcher
    nirius
    nix
    nixbang
    nixd
    nixdoc
    nixf
    nixfmt
    nixfmt-tree
    nixops-dns
    nixseparatedebuginfod2
    nixt
    nixtract
    pkgs.nix-bash-completions
    nix-binary-cache
    nix-bisect
    nix-btm
    nix-build-uncached
    nix-bundle
    nix-check-deps
    nix-converter
    nix-deploy
    nix-derivation
    nix-diff
    nix-direnv
    nix-doc
    nix-du
    nix-eval-jobs
    nix-fast-build
    nix-forecast
    nix-generate-from-cpan
    nix-health
    nix-heuristic-gc
    nix-index
    nix-init
    nix-info
    nix-info-tested
    nix-janitor
    nix-ld
    nix-lib-nmd
    nix-lib-nmt
    nix-melt
    nix-pin
    nix-playground
    nix-plugins
    nix-prefetch
    nix-prefetch-bzr
    nix-prefetch-cvs
    nix-prefetch-docker
    nix-prefetch-git
    nix-prefetch-github
    nix-prefetch-hg
    nix-prefetch-scripts
    nix-prefetch-svn
    nix-required-mounts
    nix-script
    nix-search
    nix-search-tv
    nix-snapshotter
    nix-store-veritysetup-generator
    nix-top
    nix-tree
    nix-unit
    nix-update
    nix-update-source
    nix-weather
    nix-your-shell
    nixos-anywhere
    nixos-facter
    nixos-generators
    nixos-icons
    nixos-init
    nixos-install
    nixos-install-tools
    nixos-option
    #pkgs.nixos-rebuild
    #pkgs.nixos-rebuild-ng
    nixos-shell
    nixpkgs-fmt
    nixpkgs-hammering
    nixpkgs-lint
    nixpkgs-openjdk-updater
    nixpkgs-pytools
    nixpkgs-vet
    nixt
    nixtract
    nls
    njq
    node2nix
    nodejs_latest
    nodePackages_latest.mathjax
    noisetorch
    notmuch
    nox
    nm-file-secret-agent
    nmgui
    npingler
    npins
    nps
    nurl
    nvidia-texture-tools
    nvimpager
    nvfetcher
    nvfancontrol
    nvidia_cg_toolkit
    nvidia-container-toolkit
    nvidia-docker
    nvidia-mig-parted
    nvidia-modprobe
    nvidia_oc
    nvidia-optical-flow-sdk
    nvidia-system-monitor-qt
    nvidia-vaapi-driver
    nvtopPackages.intel
    nvtopPackages.nvidia
    nvtopPackages.v3d
    nvtopPackages.full
    nwg-displays
    nwg-icon-picker
    nwg-menu
    nyx
    obs-studio
    obs-studio-plugins.looking-glass-obs
    obs-studio-plugins.obs-3d-effect
    obs-studio-plugins.obs-backgroundremoval
    obs-studio-plugins.obs-browser-transition
    obs-studio-plugins.obs-composite-blur
    obs-studio-plugins.obs-gstreamer
    obs-studio-plugins.input-overlay
    obs-studio-plugins.obs-markdown
    obs-studio-plugins.obs-media-controls
    obs-studio-plugins.obs-noise
    obs-studio-plugins.obs-pipewire-audio-capture
    obs-studio-plugins.obs-recursion-effect
    obs-studio-plugins.obs-rgb-levels
    obs-studio-plugins.obs-scale-to-sound
    obs-studio-plugins.obs-source-record
    obs-studio-plugins.obs-source-switcher
    obs-studio-plugins.obs-text-pthread
    obs-studio-plugins.obs-vkcapture
    obs-studio-plugins.obs-vaapi
    obs-studio-plugins.obs-vnc
    obs-studio-plugins.waveform
    ocamlPackages.xdg
    ocamlPackages.async_kernel
    ode
    omnix
    opam
    opencolorio
    opengrok
    openjade
    openscad-lsp
    opensmtpd-table-redis
    opensmtpd-table-socketmap
    opensmtpd-table-sqlite
    opensplatWithCuda
    openssh
    openssl
    openssl_3
    pkgs.openssl_legacy
    pkgs.openzone-cursors
    #optnix
    optinix
    oqs-provider
    os-agent
    osslsigncode
    OVMFFull
    package-version-server
    pacman
    pam
    pam_gnupg
    pam_mktemp
    pam_mount
    pam_mysql
    pam_p11
    pam_rssh
    pam_rundir
    pam_ssh_agent_auth
    pam_tmpdir
    pam_u2f
    pamtester
    pandoc
    papirus-folders
    papirus-icon-theme
    parallel-hashmap
    parallel-full
    pass-git-helper
    pass-wayland
    passExtensions.pass-update
    passExtensions.pass-import
    #patchage
    pavucontrol
    pkgs.perlPackages.TestSimple
    pkgs.perlPackages.TestMore
    pkgs.perlPackages.TestHarness
    pkgs.perlPackages.TestException
    pkgs.perlPackages.TestDeep
    pkgs.perlPackages.TestDifferences
    #perl540Packages.CPAN
    #perl540Packages.Test2Harness
    #perl
    #perl-debug-adapter
    #perlnavigator
    perf
    pfixtools
    pgf-umlcd
    phinger-cursors
    php
    picotts
    pied
    pinentry-all
    pinentry-dmenu
    piper-tts
    pkg
    pkg-configUpstream
    pkgconf
    plantuml-server
    playerctl
    pied
    pipecontrol
    pipewire
    pixelorama
    pciutils
    pcscliteWithPolkit
    polkit_gnome
    poppler
    poppler_data
    poppler_gi
    poppler-utils
    postfix
    postfix-tlspol
    postgres-lsp
    postgresql
    postgresql_18
    postgresql_jdbc
    postgres-lsp
    postgres-websockets
    postgrey
    postsrsd
    prefetch-npm-deps
    prisma-language-server
    procmail
    protonplus
    protontricks
    protonup-ng
    pssh
    pulseaudioFull
    pwvucontrol
    pw-volume
    pyenv
    #python313
    #python-packages
    pxz
    qadwaitadecorations
    qadwaitadecorations-qt6
    qastools
    qt5.qtwayland
    qt6.qtbase
    qt6.qtshadertools
    qt6.qtwayland
    qt6.qtwebengine
    qt6Packages.qtshadertools
    qt6Packages.qtstyleplugin-kvantum
    quiet
    renoise
    repro-get
    rewaita
    ripgrep-all
    rnnoise
    rnnoise-plugin
    rofi
    rustup
    rspamd
    ocl-icd
    ragenix
    rattler-build
    readline
    rebuilderd
    rescript-language-server
    rofi
    rootlesskit
    rosenpass
    roslyn-ls
    rtaudio
    rtaudio_6
    ruby-lsp
    ruff
    rune-languageserver
    samurai
    sbclPackages.cl-opengl
    sccache
    scotch
    sbt
    sbt-extras
    scalafix
    serve
    serve-d
    session-desktop
    #searxng
    shared-mime-info
    simp1e-cursors
    shaderc
    shh
    simpleBluez
    sink-rotate
    skeema
    slint-lsp
    slurp
    social-engineer-toolkit
    sof-firmware
    sof-tools
    soft-serve
    sonarlint-ls
    sops
    sourcekit-lsp
    spectral-language-server
    speexdsp
    spf-engine
    spiped
    spfft
    sqlcipher
    sqldiff
    sqlint
    sqlite
    sqlitecpp
    sqlite-utils
    sqlite-analyzer
    sqlite3-to-mysql
    sqls
    shadow
    ssh-agents
    sshd-openpgp-auth
    sshesame
    sshportal
    ssh-copy-id
    ssh-openpgp-auth
    sshd-openpgp-auth
    ssh-to-age
    ssh-to-pgp
    ssh-tools
    ssh-tpm-agent
    sslmate-agent
    statix
    steam
    steam-devices-udev-rules
    stripe-cli
    stt
    stylelint-lsp
    styx
    svelte-language-server
    svlint
    sunsetr
    super-slicer-latest
    super-tiny-icons
    superhtml
    swappy
    sway
    swaycons
    swaylock
    swaynotificationcenter
    sweet-folders
    swig
    switch-to-configuration-ng
    swww
    symlinks
    sysprof
    systembus-notify
    systemctl-tui
    systemd
    systemd-language-server
    systemd-lsp
    systemd-manager-tui
    systemdLibs
    tdlib
    telegram-desktop
    terraform-lsp
    terraform-mcp-server
    terranix
    pkgs.texinfo
    texlab
    texlive.combined.scheme-full
    biber
    ghostscript
    tailwindcss-language-server
    testlib
    testssl
    textlsp
    themix-gui
    thrift-ls
    thunderbird-latest
    tika
    timescaledb-parallel-copy
    timescaledb-tune
    tinycompress
    tk
    tlp
    tmux
    tombi
    toml2nix
    topgrade
    tor-browser
    tracy
    tree
    trlib
    trousers
    truecrack-cuda
    ts_query_ls
    ttags
    tts
    tvm
    ty
    typescript-language-server
    uhd
    ultrablue-server
    unbound-with-systemd
    ungoogled-chromium
    unix-privesc-check
    unixODBC
    unixODBCDrivers.mariadb
    unixODBCDrivers.psql
    unixODBCDrivers.sqlite
    #unzip
    update-nix-fetchgit
    upgrade-assistant
    urdfdom-headers
    usbkvm
    util-linux
    uv
    uvccapture
    uwsm
    uwufetch
    usbutils
    vala-language-server
    valkey
    vencord
    veridian
    vesktop
    vim
    vim-language-server
    vimix-icon-theme
    v4l-utils
    v4l2-relayd
    v4l2-to-ndi
    vagrant
    vcg
    virglrenderer
    vivaldi
    vivaldi-ffmpeg-codecs
    vscode-json-languageserver
    vscode-langservers-extracted
    vulnix
    waifu2x-converter-cpp
    wallust
    wasm-language-tools
    wasmserve
    waybar
    wayland
    waylandpp
    waylevel
    wayland-logout
    wayland-pipewire-idle-inhibit
    wayland-protocols
    wayland-scanner
    webrtc-audio-processing
    wev
    wget
    wgsl-analyzer
    whisparr
    wireguard-tools
    wireless-regdb
    wiremix
    wireplumber
    wl-clipboard
    wl-clip-persist
    wlogout
    wofi
    worker
    wivrn
    x11_ssh_askpass
    x264
    x265
    xarchiver
    xcursor-pro
    xdg-desktop-portal-hyprland
    xdg-dbus-proxy
    xdg-launch
    xdg-ninja
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-shana
    xdg-desktop-portal-termfilechooser
    xdg-terminal-exec
    xdg-user-dirs
    xdg-user-dirs-gtk
    xdg-utils-cxx
    xdg-utils
    xdgcpp
    xdgmenumaker
    xed
    xgboostWithCuda
    pkgs.xgc
    xkbutils
    pkgs.xmake
    xmedcon
    pkgs.xorg.gccmakedep
    pkgs.xorg.libxcb
    xorg.xkbutils
    xssproxy
    xwayland
    yad
    yaml2nix
    yamllint
    yaml-language-server
    yara
    yarn2nix
    yt-dlp
    ytmdl
    zig
    #zip
    zita-alsa-pcmi
    zlib
    zls
    zoom-us
    zon2nix
    zotero
    zotero-translation-server
    zoxide
    zram-generator
    zsh
    zvm
  ];
}
