# core.nix
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    _64gram
    abseil-cpp
    #acl
    #adbfs-rootless
    #add-determinism
    adw-gtk3
    adwaita-fonts
    adwaita-icon-theme
    adwaita-icon-theme-legacy
    adwaita-qt
    adwaita-qt6
    adwsteamgtk
    afew
    #agate
    #agenix-cli
    #alot
    alsa-lib
    alsa-lib-with-plugins
    alsa-oss
    alsa-plugins
    audacity
    #backgroundremover
    bash
    bash-completion
    blueman
    bluetuith
    bluez
    bluez-alsa
    bluez5
    bluez5-experimental
    bluez-headers
    bluez-tools
    #clang
    #cmake
    #coreutils
    dconf
    direnv
    #exo
    fish
    firefox
    #flat-remix-icon-theme
    fuse
    fuzzel
    fzf
    glibc
    #gdk-pixbuf
    git
    hyprland
    #javacc
    #jdk
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    librsvg
    libidn2
    #libGL
    limine
    linux-firmware
    lfs
    #looking-glass-client
    maturin
    microcode-intel
    neovim
    networkmanager
    networkmanagerapplet
    #networkmanager_dmenu
    #networkmanager-iodine
    #networkmanager-l2tp
    #networkmanager-openconnect
    #networkmanager-strongswan
    #nh
    #ninja
    niri
    niriswitcher
    nirius
    nix
    #nix-index
    #nix-ld
    #noisetorch
    obs-studio
    #obs-studio-plugins.looking-glass-obs
    #obs-studio-plugins.obs-3d-effect
    #obs-studio-plugins.obs-backgroundremoval
    ##obs-studio-plugins.obs-browser-transition
    #obs-studio-plugins.obs-composite-blur
    #obs-studio-plugins.obs-gstreamer
    #obs-studio-plugins.input-overlay
    #obs-studio-plugins.obs-markdown
    #obs-studio-plugins.obs-media-controls
    #obs-studio-plugins.obs-noise
    #obs-studio-plugins.obs-pipewire-audio-capture
    #obs-studio-plugins.obs-recursion-effect
    #obs-studio-plugins.obs-rgb-levels
    #obs-studio-plugins.obs-scale-to-sound
    #obs-studio-plugins.obs-source-record
    #obs-studio-plugins.obs-source-switcher
    #obs-studio-plugins.obs-text-pthread
    #obs-studio-plugins.obs-vkcapture
    #obs-studio-plugins.obs-vaapi
    #obs-studio-plugins.obs-vnc
    #obs-studio-plugins.waveform
    openssl
    pipewire
    pinentry-all
    #pkgs.python313FreeThreading
    #python3Minimal
    #schroot
    #seahorse
    #stow
    #steam
    #sway
    #systemd
    #systemdLibs
    tlp
    vesktop
    #virt-manager
    #virtualenv
    waybar
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-hyprland
    #xdg-desktop-portal-shana
    #xdg-desktop-portal-termfilechooser
    ydotool
    #zlib
    zoom-us
    zoxide
    #zram-generator
    #zsh
    zvm
  ];
}
